version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez / we have on row per productid found in each orders_id
	  # Freshness testing
    loaded_at_field: "CAST(date_date AS TIMESTAMP)"
    freshness:
      warn_after: {count: 90, period: day}
    columns:
      - name: date_date
        description: date of purchase